### ISSUE TITLE
API for Tuner Status

### ISSUE THREAD

**Issue by fbradyirl** [E2OpenPlugins/e2openplugin-OpenWebif#568]
Is there an API at present for fetching all tuner status? E.g. binary 'in use' or 'idle'?

Also, is it possible to have an API to determine if the transcoder is in use, or if streaming is in use (e.g. ports 8002, 8001 in use). 

If APIs are not available, can the same be done using Linux commands?

e.g. currently I use the following command to determine if the transcoder is in use, but maybe there is an better method?
```yaml
  - platform: command_line
    command: "ssh -q root@10.10.10.10 'netstat -tn | grep 8002 | awk \"/EST/{print $5}\" | wc -l'"
    name: Vu Transcoder Active
    payload_on: 1
    payload_off: 0
    scan_interval: 60
```
